python3 simulatedAnnealing.py 0 -lt logs_datasets
python3 simulatedAnnealing.py 1 -lt logs_datasets
python3 simulatedAnnealing.py 2 -lt logs_datasets
python3 simulatedAnnealing.py 3 -lt logs_datasets
python3 simulatedAnnealing.py 4 -lt logs_datasets
python3 simulatedAnnealing.py 5 -lt logs_datasets
python3 simulatedAnnealing.py 6 -lt logs_datasets
python3 simulatedAnnealing.py 7 -lt logs_datasets
python3 simulatedAnnealing.py 8 -lt logs_datasets
python3 simulatedAnnealing.py 9 -lt logs_datasets
python3 simulatedAnnealing.py 10 -lt logs_datasets
python3 simulatedAnnealing.py 11 -lt logs_datasets
python3 simulatedAnnealing.py 12 -lt logs_datasets
python3 simulatedAnnealing.py 13 -lt logs_datasets
python3 simulatedAnnealing.py 14 -lt logs_datasets
python3 simulatedAnnealing.py 15 -lt logs_datasets
python3 simulatedAnnealing.py 16 -lt logs_datasets
